{/* 
    Index home page to trigger API
*/}
import Image from 'next/image'
import Modal from '@/components/modal'
import React, { useState } from "react";
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [showModal, setShowModal] = useState(false);

  return (
    
    <main>
      <Head>
        <title>Bezel: View Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-bezel.png" />
      </Head>

      <Image src={'/logo-bezel.png'} width={100} height={100} className='p-6' alt=''/>

       {/* Modal Trigger */}
      <div className='px-8 py-4'>
        <button onClick={() => setShowModal(true)} className='w-full py-2 m-2.5 bg-gray-100 hover:bg-gray-200 rounded-md'>
            Open Order
        </button>
      </div>

      {/* Modal */}
      <Modal isvisable={showModal} onClose={()=> setShowModal(false)}/>
    </main>
  )
}
